### PR TITLE
Add SFTP_UID var to change sftp uid at runtime

### PR DESCRIPTION
**Pull request by Vampouille**
This PR :
- add variable SFTP_UID to change uid of sftp user
- add documentation about configuration of this image
- re-order bootstrap scripts

### CODE REVIEW

**Comment by Vampouille** [comment]
@mcanevet can you merge this pr ?

**Comment by mcanevet** [comment]
@Vampouille please remove the fix permission removal (explanation in the other PR)

**Comment by Vampouille** [comment]
@mcanevet it's done. Can you review this pr ?

**Comment by mcanevet** [comment]
LGTM

**Pull request merged**
