### PR TITLE
Add rsync

### PR DESCRIPTION
**Pull request by pmauduit**
It can be interesting to have such a tool to copy data to the container.

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Please review

**Comment by Vampouille** [comment]
LGTM @mcanevet

**Comment by mcanevet** [comment]
This container is for sftp, if you need another protocol it has to go to another container

**Comment by pmauduit** [comment]
But rsync as a client can be used over ssh, it seems legit to have such a tool in this container, regardless of the protocol question.

In addition, multiplying stacks involves adding memory footprint of each component each time, where in this case it can be factored IMHO.

**Comment by mcanevet** [comment]
@pmauduit this container is restricted to sftp for security reasons

**Comment by Vampouille** [comment]
@mcanevet If we build a new nas image with rsync as "protocol" we will also have sftp protocol enable. sftp and rsync only allow files modification, can you explain what security breach rsync introduce ?

**Comment by mcanevet** [comment]
@Vampouille I think you'd better have you own image than and not use this one. This one is dedicated to sftp.

**Pull request closed without merging**
