### PR TITLE
Add symlink to named volume in sftp user homedir

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by fvanderbiest** [comment]
LGTM, please merge

**Comment by Vampouille** [comment]
@mcanevet can you also merge this pr ?

**Comment by mcanevet** [comment]
This is opinionated and I'd like to keep this container as generic as possible.
Maybe we could keep user in a chroot jail which would be configured at runtime?

**Comment by Vampouille** [comment]
implemented in https://github.com/camptocamp/georchestra-sftp

**Pull request closed without merging**
